#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 (loadbalancer) server using roundrobbin algorithm

sudo apt-get -y update
apt-get -y install haproxy

# edit .config file
server_config=\
"
frontend divinelewis.tech-frontend
        bind *:80
        mode http
        default_backend divinelewis.tech-backend
backend divinelewis.tech-backend
        balance roundrobin
        server 173867-web-01 52.91.145.188 check
        server 173867-web-02 100.25.137.235 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
